background {
    monitor =
    color = rgba(46, 52, 64, 1.0)
}

input-field {
    monitor =
    size = 250, 40
    outline-thickness = 2
    dots-size = 0.25
    dots-spacing = 0.3
    outer-color = rgb(76, 86, 106)
    inner-color = rgb(59, 66, 82)
    font-color = rgb(216, 222, 233)
    fade-on-empty = false
    placeholder-text = <i>Password</i>
    check-color = rgb(163, 190, 140)
    fail-color = rgb(191, 97, 106)
    fail-text = <i>$FAIL ($ATTEMPTS)</i>
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(216, 222, 233, 1.0)
    font-size = 48
    font-family = JetBrains Mono
    position = 0, 80
    halign = center
    valign = center
}
