# Hyprland config — Intel Celeron N4020, UHD 600, 4 GB RAM

source = ~/.config/hypr/conf.d/monitor.conf
source = ~/.config/hypr/conf.d/startup.conf
source = ~/.config/hypr/conf.d/input.conf
source = ~/.config/hypr/conf.d/appearance.conf
source = ~/.config/hypr/conf.d/colors.conf
source = ~/.config/hypr/conf.d/keybinds.conf
