general {
    gaps_in  = 5
    gaps_out = 10
    border_size = 2
    col.active_border   = rgba(88C0D0ff) rgba(5E81ACff) 45deg
    col.inactive_border = rgba(3B4252ff)
    layout = dwindle
}

decoration {
    rounding = 12
    shadow {
        enabled      = true
        range        = 10
        render_power = 2
        color        = rgba(1E222Aee)
    }
    blur {
        enabled = false   # save GPU on UHD 600
    }
    screen_shader = ~/.config/hypr/shaders/anti-flashbang.glsl
}

animations {
    enabled = true
    bezier = smooth,   0.05, 0.9, 0.1, 1.05
    bezier = snappy,   0.25, 1.0, 0.5, 1.0
    animation = windows,    1, 4, smooth,  slide
    animation = windowsOut, 1, 3, snappy,  slide
    animation = fade,       1, 4, default
    animation = workspaces, 1, 4, snappy,  slide
}

dwindle {
    pseudotile     = true
    preserve_split = true
}
