# Autostart
exec-once = waybar
exec-once = pipewire
exec-once = pipewire-pulse
exec-once = wireplumber
exec-once = mako
exec-once = hypridle
exec-once = swww-daemon
exec-once = bash -c 'sleep 0.3; [[ -f ~/.config/hypr/wallpaper.jpg ]] && swww img ~/.config/hypr/wallpaper.jpg --transition-type fade --transition-duration 1.5'
exec-once = wl-paste --type text --watch cliphist store

# Variables
$terminal = kitty
$launcher = wofi --show drun

# Environment
env = LIBVA_DRIVER_NAME,i965
env = WLR_DRM_NO_ATOMIC,1        # needed on older Intel iGPUs
env = XDG_SESSION_TYPE,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
