# Autostart
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = waybar
exec-once = pipewire
exec-once = pipewire-pulse
exec-once = wireplumber
exec-once = easyeffects --service
exec-once = swaync
exec-once = hypridle
exec-once = awww-daemon
exec-once = bash -c 'sleep 0.3; [[ -f ~/.config/hypr/wallpaper.jpg ]] && awww img ~/.config/hypr/wallpaper.jpg --transition-type fade --transition-duration 1.5'
exec-once = wl-paste --type text --watch cliphist store
exec-once = nwg-dock-hyprland -p bottom -i 40 -mb 8 -d -nolauncher -s style.css
exec-once = hyprsunset
exec-once = swayosd-server
exec-once = node /home/jorrell/arch-rpc/index.js

# Apply GTK theme, icons, cursor, dark mode via gsettings
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'
exec-once = gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Classic'
exec-once = gsettings set org.gnome.desktop.interface cursor-size 20
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

# Variables
$terminal    = kitty
$launcher    = rofi -show drun
$fileManager = thunar
$browser     = firefox
$codeEditor  = code

# Environment
env = LIBVA_DRIVER_NAME,i965
env = WLR_DRM_NO_ATOMIC,1        # needed on older Intel iGPUs
env = XDG_SESSION_TYPE,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,20
env = GTK_THEME,adw-gtk3-dark
env = PASSWORD_STORE,gnome-keyring
