CATEGORIES = [
    {
        "id": "hyprland",
        "label": "Hyprland",
        "subtitle": "hyprland.conf, conf.d/, scripts/",
        "paths": ["~/.config/hypr"],
        "enabled": True,
    },
    {
        "id": "waybar",
        "label": "Waybar",
        "subtitle": "Bar config and CSS",
        "paths": ["~/.config/waybar"],
        "enabled": True,
    },
    {
        "id": "kitty",
        "label": "Kitty",
        "subtitle": "Terminal config and theme",
        "paths": ["~/.config/kitty"],
        "enabled": True,
    },
    {
        "id": "wofi",
        "label": "Wofi",
        "subtitle": "App launcher config",
        "paths": ["~/.config/wofi"],
        "enabled": True,
    },
    {
        "id": "fuzzel",
        "label": "Fuzzel",
        "subtitle": "App launcher config",
        "paths": ["~/.config/fuzzel"],
        "enabled": True,
    },
    {
        "id": "mako",
        "label": "Mako",
        "subtitle": "Notification daemon config",
        "paths": ["~/.config/mako"],
        "enabled": True,
    },
    {
        "id": "swaync",
        "label": "SwayNC",
        "subtitle": "Notification center config",
        "paths": ["~/.config/swaync"],
        "enabled": True,
    },
    {
        "id": "fish",
        "label": "Fish Shell",
        "subtitle": "Fish config and functions",
        "paths": ["~/.config/fish"],
        "enabled": True,
    },
    {
        "id": "zsh",
        "label": "Zsh",
        "subtitle": ".zshrc",
        "paths": ["~/.zshrc"],
        "enabled": False,
    },
    {
        "id": "starship",
        "label": "Starship",
        "subtitle": "Prompt config",
        "paths": ["~/.config/starship.toml"],
        "enabled": True,
    },
    {
        "id": "gtk",
        "label": "GTK Theme",
        "subtitle": "GTK 2/3/4 settings",
        "paths": ["~/.config/gtk-3.0", "~/.config/gtk-4.0", "~/.gtkrc-2.0"],
        "enabled": False,
    },
    {
        "id": "wallpaper",
        "label": "Wallpaper",
        "subtitle": "Current wallpaper image",
        "paths": ["~/.config/hypr/wallpaper.jpg"],
        "enabled": False,
    },
]
